### ISSUE TITLE
Support building from path to a mine instead of git repo

### ISSUE THREAD

**Issue by heralden** [intermine/intermine_boot#29]
It seems important to be able to build a mine by its path instead of passing a git repo as an argument.

We would have to add a new argument for this, and handle it by creating a volume to mount that dir in the intermine_builder container.

**Comment by 22PoojaGaur** [comment]
Hi @uosl 

I think this would require two changes -
1) Adding and passing flag for the path in intermine_boot
2) Updating build.sh in docker-intermine-gradle to go into that folder if path is specified.

Does it seem fair to you? or am I missing something?

**Comment by 22PoojaGaur** [comment]
For changes in docker-intermine-gradle, I still create a PR in the docker-intermine-repo right?

(And somehow update the git submodule to fetch that version in intermine_boot?)

**Comment by heralden** [comment]
> Adding and passing flag for the path in intermine_boot

:+1: 

> Updating build.sh in docker-intermine-gradle to go into that folder if path is specified

Not sure about this, since we'll need to make the dir available by passing it as a volume. Currently, we mount a biotestmine volume and cd into it, right? I think we should mount a volume with the dir the path points to, and cd into that (which should only be one level deep).

> For changes in docker-intermine-gradle, I still create a PR in the docker-intermine-repo right?
> (And somehow update the git submodule to fetch that version in intermine_boot?)

:+1: 
For testing you might want to replace the submodule with a symlink to your local docker-intermine-repo folder, as I'm not sure how easy it is to get a submodule to stay up-to-date with your local repo when you're trying things out.

**Comment by 22PoojaGaur** [comment]
> Not sure about this, since we'll need to make the dir available by passing it as a volume. Currently, we mount a biotestmine volume and cd into it, right? I think we should mount a volume with the dir the path points to, and cd into that (which should only be one level deep).

oh, right. If the folder `biotestmine` (or MINE_NAME) exist it should be able to use it. I'll see.

> For testing you might want to replace the submodule with a symlink to your local docker-intermine-repo folder, as I'm not sure how easy it is to get a submodule to stay up-to-date with your local repo when you're trying things out.

ok.

**Comment by 22PoojaGaur** [comment]
@uosl 

I added a flag for datapath (datapath is a folder under which `biotestmine` would be present). If the flag is provided, it loads the datapath instead of creating new volumes.

For testing I just cloned the biotestmine repo in a datapath folder and pass datapath as command line argument. I think this is not sufficient, as other folders (eg dump, configs, packages) are required during intermine build.

So my question is, in building mine from path do I assume that these folders are present and the intermine_boot just needs to start the webapp ?

If not, what should I do?

**Comment by heralden** [comment]
I think the datapath folder should only replace the `biotestmine` volume, while the other volumes (dump, configs, packages, and intermine) should still be created and loaded as volumes.

Let me know if I misunderstood and this doesn't answer your question clearly.

**Comment by 22PoojaGaur** [comment]
Yes, that's what I was asking. 

Got it.
