### ISSUE TITLE
--build-im doesn't seem to work

### ISSUE THREAD

**Issue by heralden** [intermine/intermine_boot#34]
As a reminder, `--build-im` builds InterMine before building Biotestmine (so a custom build of InterMine can be used to build Biotestmine).

This might be simply because the dockerhub containers are outdated, so we should test this again combined with `--build-images` once #33 is fixed.

**Comment by 22PoojaGaur** [comment]
Hi @uosl 

what is the difference  between `--build-im` and `--build-images` flags?

Their help definition looks similar to me (given how we are building mine).

**Comment by heralden** [comment]
`--build-im` specifies that you want to build a custom version of InterMine (usually you'll use `--im-repo` and/or `--im-branch` to point to your fork of Intermine which differs from the official one uploaded to maven, that is fetched automatically when building a mine). By *Intermine* here, I don't mean a mine instance like Biotestmine, but the actual program that is used to build a mine instance.

`--build-images` specifies that you want to build the docker images from the dockerfiles, instead of pulling the prebuilt images from dockerhub.

We could probably improve their help definition, or rename *im* to *intermine* to be less ambiguous. (I think at some point we're going to redo all the flags and arguments to make things clearer, probably when we do a major release.)

I will look into this issue again once I've had a look at #33, as they might be related.

**Comment by heralden** [comment]
This also works with the submodule initialized!
