### ISSUE TITLE
Add CI end-to-end tests for common usecases

### ISSUE THREAD

**Issue by heralden** [intermine/intermine_boot#36]
I was a bit reluctant to suggest this to begin with, since they take 15-30 minutes each to run, and if Travis is feeling overloaded it will happily fail them even though nothing is wrong. Optimally, they should also all run in parallel so it won't take 1 hour to run.

Bonus: Look into implementing this with GitHub Actions instead of Travis, which hopefully is more stable.

Here are the commands we should test:
- `intermine_boot start local`
- `intermine_boot start local --build-im`
- `intermine_boot start local --build-images`

These all should be followed by running an HTTP request (probably with curl) to http://localhost:9999/biotestmine and checking for valid response.

**Comment by 22PoojaGaur** [comment]
Hi @uosl 
[Status update]
I am using github actions to do this. I have done the official github actions tutorial. I have also written workflow to test `intermine_boot start local`

Right now, looking at why it's failing.
