### ISSUE TITLE
Compare and document performance of different compression formats

### ISSUE THREAD

**Issue by leoank** [intermine/intermine_boot#5]
## Problem
We are creating archives of data created by containers for reusing them in future builds.
But, we are not sure which compression format to choose.

## Outline of a Solution
Add a markdown that contains a table comparing parameters like speed and ratio of different compression algorithms.

**Comment by Samiratu** [comment]
Hello, @leoank  I want to work on this but I will like to know if I have to do some setup before I can work on it and how to go about that setup.

**Comment by Samiratu** [comment]
Basically I want to know what software to install and some guides on how to install them in order to get started.

**Comment by Samiratu** [comment]
@leoank I will like to inquire if this project has been assigned to someone or I can work on it.

and also a guide on how to set up my own local repository so that I can start contributing.

**Comment by heralden** [comment]
Hello @Samiratu. You can start by cloning this repo and following the instructions in the README. Basically, install the dependencies under *Requirements* and run the commands under *Development* inside a terminal.

Once you get the project running, use the command `intermine_boot build local` to build and archive an InterMine instance, saving the archives to `intermine_boot` in `XDG_DATA_HOME` (use a search engine to find out which folder this is on your operating system). Then modify the code in https://github.com/intermine/intermine_boot/blob/2d9b6ebe3cd0a1e88897df74e3dfbce42ab1dcbe/intermine_boot/docker.py#L82 to try different compression formats. Refer to the [python docs](https://docs.python.org/3.5/library/shutil.html#shutil.make_archive) for the formats available.

Make sure to record the time and resulting file sizes of compressing each format, and put them in a table in a markdown file, along with the CPU model of your computer, so we have a basis for comparison.

**Comment by Samiratu** [comment]
Thanks @uosl . I just did the things you have mentioned but I still can't run the project. please find below a screenshot of what I get. I also have a question since this is a python project can I use an IDE such as pycharm for it?
![git](https://user-images.githubusercontent.com/43297376/76902102-edfd9b80-68a3-11ea-814f-8793cecc1d3d.png)

And please tell me what I can do to get the project running.

**Comment by Samiratu** [comment]
![intermine_boot1](https://user-images.githubusercontent.com/43297376/76904035-db856100-68a7-11ea-90b4-b915c418d246.png)
sorry about the first attachment here is the correct one

**Comment by leoank** [comment]
@Samiratu you are spelling it wrong. You should type `intermine_boot` **NOT** `intermine-boot`. Also, You can use pycharm if you want to.

**Comment by niveditarufus** [comment]
Hello @leoank, @uosl  I just tried out different compression formats : tar, bztar, gztar, xztar and zip for the archiveing the files biotestmine, postgres and solr respectively and given below is the report of my analysis:

report:
|     **File**    	| **Format** 	| **Time taken to compress(s)** 	| **Size after compression(MB)** 	|
|:---------------:	|:----------:	|:-----------------------------:	|:------------------------------:	|
| **biotestmine** 	|     tar    	|             1.069             	|               231              	|
| **biotestmine** 	|    bztar   	|             9.329             	|               201              	|
| **biotestmine** 	|    gztar   	|             3.463             	|               202              	|
| **biotestmine** 	|    xztar   	|             19.930            	|               196              	|
| **biotestmine** 	|     zip    	|              3.79             	|               204              	|
|                 	|            	|                               	|                                	|
|   **postgres**  	|     tar    	|             1.497             	|               567              	|
|   **postgres**  	|    bztar   	|             2.101             	|               77               	|
|   **postgres**  	|    gztar   	|             5.733             	|               96               	|
|   **postgres**  	|    xztar   	|             7.962             	|               50               	|
|   **postgres**  	|     zip    	|             2.703             	|               98               	|
|                 	|            	|                               	|                                	|
|     **solr**    	|     tar    	|             0.0255            	|               59               	|
|     **solr**    	|    bztar   	|             0.0788            	|               9.8              	|
|     **solr**    	|    gztar   	|             0.074             	|               12               	|
|     **solr**    	|    xztar   	|             0.112             	|               8.0              	|
|     **solr**    	|     zip    	|             0.177             	|               12               	|
|                 	|            	|                               	|                                	|


cpu model: 
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              8
On-line CPU(s) list: 0-7
Thread(s) per core:  2
Core(s) per socket:  4
Socket(s):           1
NUMA node(s):        1
Vendor ID:           GenuineIntel
CPU family:          6
Model:               158
Model name:          Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
Stepping:            9
CPU MHz:             800.038
CPU max MHz:         3800.0000
CPU min MHz:         800.0000
BogoMIPS:            5599.85
Virtualization:      VT-x
L1d cache:           32K
L1i cache:           32K
L2 cache:            256K
L3 cache:            6144K
NUMA node0 CPU(s):   0-7
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb invpcid_single pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp md_clear flush_l1d

**Comment by heralden** [comment]
Closing issue as this was fixed in #18.
